/**
 * Mechanical audit checks.
 *
 * Pure functions over a diff and a file list, so every rule here is unit
 * testable without a network, a clone, or a pull request. The orchestration in
 * gate.ts does the impure work of fetching and running commands.
 *
 * Each check encodes a rule this project already states somewhere in prose. The
 * value is not that a machine can read prose; it is that a rule nobody can
 * forget to apply is worth more than a rule everybody agrees with.
 */

export interface Finding {
  /** Stable identifier, used in comments so a repeat offence is recognisable. */
  code: string;
  severity: "block" | "warn";
  file: string | null;
  line: number | null;
  message: string;
}

export interface AddedLine {
  file: string;
  line: number;
  text: string;
}

/**
 * Extract added lines from a unified diff.
 *
 * Only added lines are audited. A rule that fires on removed lines would block
 * a pull request for deleting the very thing the rule dislikes, which is the
 * opposite of the intent.
 */
export function addedLines(unifiedDiff: string): AddedLine[] {
  const added: AddedLine[] = [];
  let file: string | null = null;
  let lineNumber = 0;

  for (const raw of unifiedDiff.split("\n")) {
    if (raw.startsWith("+++ b/")) {
      file = raw.slice("+++ b/".length).trim();
      continue;
    }
    if (raw.startsWith("--- ") || raw.startsWith("diff --git")) continue;

    const hunk = raw.match(/^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@/);
    if (hunk?.[1]) {
      lineNumber = Number(hunk[1]);
      continue;
    }

    if (raw.startsWith("+")) {
      if (file) added.push({ file, line: lineNumber, text: raw.slice(1) });
      lineNumber += 1;
    } else if (raw.startsWith(" ")) {
      lineNumber += 1;
    }
  }

  return added;
}

const TEXT_EXTENSIONS = [".md", ".ts", ".tsx", ".js", ".json", ".yml", ".yaml", ".java"];

function isText(file: string): boolean {
  return TEXT_EXTENSIONS.some((extension) => file.endsWith(extension));
}

/** House style: em dashes are not used anywhere in this repository. */
export function checkEmDashes(added: readonly AddedLine[]): Finding[] {
  return added
    .filter((entry) => isText(entry.file) && entry.text.includes("—"))
    .map((entry) => ({
      code: "em_dash",
      severity: "block" as const,
      file: entry.file,
      line: entry.line,
      message:
        "Em dash in an added line. Use a colon, semicolon, comma, parentheses, or split the sentence.",
    }));
}

const AUTHORSHIP_PATTERNS = [
  /co-authored-by:/i,
  /generated with \[?claude/i,
  /\bgenerated by (?:an? )?(?:ai|assistant|claude|llm)\b/i,
  /\bas an ai\b/i,
];

/** Authorship notes and assistant trailers do not belong in the tree. */
export function checkAuthorshipNotes(added: readonly AddedLine[]): Finding[] {
  return added
    .filter((entry) => AUTHORSHIP_PATTERNS.some((pattern) => pattern.test(entry.text)))
    .map((entry) => ({
      code: "authorship_note",
      severity: "block" as const,
      file: entry.file,
      line: entry.line,
      message: "Authorship note or assistant trailer in an added line. Remove it.",
    }));
}

/**
 * Strip a line to its code, so a rule cannot fire on a comment that merely names
 * the thing it forbids. A file explaining why there is no bypass would otherwise
 * be blocked for saying so, which is the most annoying kind of false positive:
 * it punishes the person who documented the rule.
 */
function codeOnly(text: string): string {
  return text
    .replace(/\/\/.*$/, "")
    .replace(/\/\*.*?\*\//g, "")
    .replace(/^\s*\*.*$/, "")
    .trim();
}

function isTestFile(file: string): boolean {
  return file.includes("/test/") || file.endsWith(".test.ts");
}

/**
 * Project invariants that a passing test suite would not catch, because the test
 * that would catch them is exactly the test somebody would delete.
 *
 * Test files are exempt from the identifier checks. A test asserting that no
 * bypass exists has to name the bypass to assert it is absent.
 */
export function checkInvariants(added: readonly AddedLine[]): Finding[] {
  const findings: Finding[] = [];

  for (const entry of added) {
    const code = codeOnly(entry.text);
    if (code === "") continue;

    // The model emits rule documents, never Java. Match only signals that are
    // unambiguously Java: "class" alone is not one, TypeScript has classes too.
    if (
      entry.file.startsWith("packages/authoring/") &&
      !isTestFile(entry.file) &&
      /(?:public\s+(?:static\s+)?(?:void|class)\b|import\s+org\.bukkit|@Override\b|extends\s+JavaPlugin\b)/.test(
        code,
      )
    ) {
      findings.push({
        code: "java_generation",
        severity: "block",
        file: entry.file,
        line: entry.line,
        message:
          "Looks like Java is being generated or templated in the authoring package. The model emits validated JSON documents only.",
      });
    }

    // Raw world events are never stored. They grow without bound and nothing
    // reads them; everything downstream reads rollups.
    if (
      entry.file.includes("modules/telemetry/") &&
      !isTestFile(entry.file) &&
      /\b(?:insertRawEvent|raw_events|rawEvents|storeEvent\()/.test(code)
    ) {
      findings.push({
        code: "raw_event_storage",
        severity: "block",
        file: entry.file,
        line: entry.line,
        message:
          "Looks like raw world events are being persisted. Only rolling window aggregates are stored.",
      });
    }

    // There is no trusted-caller path around validation, and there never will be.
    if (
      !isTestFile(entry.file) &&
      /\b(?:skipValidation|bypassValidation|trustedOutput|allowUnvalidated)\b/.test(code)
    ) {
      findings.push({
        code: "validation_bypass",
        severity: "block",
        file: entry.file,
        line: entry.line,
        message:
          "Looks like a validation bypass. The validator is the only path from a rule document to a build and has no trusted-caller exception.",
      });
    }

    // Any rule class that auto-approves is a class a player can reach through
    // chat injection. Tiering and injection resistance cannot both be true.
    if (
      !isTestFile(entry.file) &&
      /\b(?:autoApprove|auto_approve|approvalTier|skipApproval)\b/.test(code)
    ) {
      findings.push({
        code: "auto_approval",
        severity: "block",
        file: entry.file,
        line: entry.line,
        message:
          "Looks like an auto-approval path. There is no auto-approval tier in v1; approval fatigue is solved by batching, not tiering.",
      });
    }
  }

  return findings;
}

/**
 * The provisional vocabulary is a stand-in that exists to be deleted. Adding
 * primitives to it means adding primitives nobody reviewed, which will be
 * dropped at swap time along with whatever was built on them.
 */
export function checkProvisionalVocabulary(added: readonly AddedLine[]): Finding[] {
  return added
    .filter(
      (entry) =>
        entry.file.endsWith("rule-document.provisional.ts") &&
        /Type\.Literal\("[a-z_]+"\)/.test(entry.text) &&
        entry.text.includes("rule:"),
    )
    .map((entry) => ({
      code: "vocabulary_widened",
      severity: "warn" as const,
      file: entry.file,
      line: entry.line,
      message:
        "A primitive may have been added to the provisional vocabulary. Widening the action space is a reviewed security change, not a stand-in edit.",
    }));
}

/** Tests are not optional on a pull request that adds source. */
export function checkTestsAccompanySource(files: readonly string[]): Finding[] {
  const source = files.filter(
    (file) =>
      (file.endsWith(".ts") || file.endsWith(".java")) &&
      !file.includes("/test/") &&
      !file.endsWith(".test.ts") &&
      !file.startsWith("fixtures/"),
  );
  const tests = files.filter((file) => file.includes("/test/") || file.endsWith(".test.ts"));

  if (source.length > 0 && tests.length === 0) {
    return [
      {
        code: "no_tests",
        severity: "warn",
        file: null,
        line: null,
        message: `Adds or changes ${source.length} source files and no tests.`,
      },
    ];
  }
  return [];
}

export function auditDiff(unifiedDiff: string, files: readonly string[]): Finding[] {
  const added = addedLines(unifiedDiff);
  return [
    ...checkEmDashes(added),
    ...checkAuthorshipNotes(added),
    ...checkInvariants(added),
    ...checkProvisionalVocabulary(added),
    ...checkTestsAccompanySource(files),
  ];
}

export function blockers(findings: readonly Finding[]): Finding[] {
  return findings.filter((finding) => finding.severity === "block");
}
